KTB-15 реализовал отправку ответов в телеграмм
Lapadoga/KotlinTelegramBot pull request #12
Opened 2024-08-28 17:02 UTC by Lapadoga

2024-08-29 12:21 UTC, kaznikit commented on src/main/kotlin/TelegramBotService.kt
> +            val urlSendMessage = "https://api.telegram.org/bot$botToken/sendMessage?chat_id=$chatId&text=$messageText"
здесь использовать константу для хоста

2024-08-29 12:25 UTC, kaznikit commented on src/main/kotlin/TelegramBotService.kt
> +    fun sendMessage(chatId: String, messageText: String): Boolean {
нам в целом не нужен ответ от этой функции, достаточно залогировать ошибку и показать ее юзеру каким-либо способом

2024-08-29 13:25 UTC, Lapadoga commented
Не до конца уверен во внесенных правках: решил вынести хост не в константу, а в переменную класса, так как ей в таком случае удобнее пользоваться, и вынес try catch из функции отправки сообщения, так как не был уверен, стоит ли возвращать текст исключения или лучше отлавливать исключение из вне

2024-08-30 05:33 UTC, kaznikit requested changes

2024-08-30 05:33 UTC, kaznikit commented on src/main/kotlin/TelegramBotService.kt
> +    private val host = "https://api.telegram.org/bot$botToken/"
использование токена вместе с хостом может сбить с толку, так как мы ожидаем что в хосте будет лежать только `https://api.telegram.org`
как вариант можно сделать дополнительную переменную `hostWithToken`, либо добавлять токен в месте использования

2024-08-30 05:33 UTC, kaznikit commented on src/main/kotlin/TelegramBotService.kt
> +        val urlGetUpdates = host + "getUpdates?offset=$updateId"
давай использовать интерполяцию для строк

2024-08-30 05:33 UTC, kaznikit commented on src/main/kotlin/TelegramBotService.kt
> +        val urlSendMessage = host + "sendMessage?chat_id=$chatId&text=$messageText"
и здесь

2024-08-30 05:35 UTC, kaznikit commented
> Не до конца уверен во внесенных правках: решил вынести хост не в константу, а в переменную класса, так как ей в таком случае удобнее пользоваться, и вынес try catch из функции отправки сообщения, так как не был уверен, стоит ли возвращать текст исключения или лучше отлавливать исключение из вне

в целом использование переменной тоже окей. с обработкой ошибок все нормально)

2024-08-31 07:31 UTC, kaznikit approved these changes

2024-08-31 08:33 UTC, merged